"""added_articles

Revision ID: 974428a1a229
Revises: 9972656fa0c6
Create Date: 2023-05-19 22:42:37.164027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974428a1a229'
down_revision = '9972656fa0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('body', sa.String(length=10000), nullable=True),
    sa.Column('tagList', sa.PickleType(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
