"""added_articles

Revision ID: 9972656fa0c6
Revises: bf9a720e5a4d
Create Date: 2023-05-19 22:41:29.233507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9972656fa0c6'
down_revision = 'bf9a720e5a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
