"""create_db

Revision ID: bf9a720e5a4d
Revises: 
Create Date: 2023-04-05 20:12:20.676313

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bf9a720e5a4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('token', sa.String(length=100), nullable=True),
        sa.Column('username', sa.String(length=100), nullable=True),
        sa.Column('password', sa.String(length=100), nullable=True),
        sa.Column('bio', sa.String(length=100), nullable=True),
        sa.Column('image', sa.String(length=100), nullable=True),
        sa.Column('following_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['following_id'],
            ['user.id'],
        ), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('email'),
        sa.UniqueConstraint('token'), sa.UniqueConstraint('username'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
